create table zai_zhang_zi_chan (
id integer not null primary key,
zi_chan_ming_cheng text not null,
zi_chan_dai_ma text not null,
lei_bie_dai_ma text not null,
lei_bie_ming_cheng text not null,
ka_pian_zhuang_tai text not null,
dan_jia real not null,
shu_liang integer not null,
zeng_jia_fang_shi text not null,
gou_zhi_ri_qi text not null,
gui_ge_xing_hao text,
shi_yong_bu_men text,
shi_yong_ren text,
cun_fang_di_dian text,
gong_huo_shang text,
shi_yong_nian_xian integer not null,
ka_pian_bian_hao text not null,
zi_chan_da_lei text not null);
